name: Cargo Publish

on:
  release:
    types: [published]

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update
    - run: cargo publish -p soroban-fixed-point-math
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}